[Interface]
PrivateKey = WAGamVkh9l1d1NaLBMYGkILpgSn/9GJdWF47STWuYV0=
Address = 10.66.66.2/32,fd42:42:42::2/128
DNS = 192.168.1.50,1.1.1.1

# Uncomment the next line to set a custom MTU
# This might impact performance, so use it only if you know what you are doing
# See https://github.com/nitred/nr-wg-mtu-finder to find your optimal MTU
# MTU = 1420

[Peer]
PublicKey = 1tLaWxfen1SJI4K90mvcpiswo8l+gPK+bLPT+Fotszc=
PresharedKey = Wi/wCcvqi9bCOjRBlLG3jwskZM4jyXZ2HS7E06j293Y=
Endpoint = 73.80.156.114:58025
AllowedIPs = 192.168.1.0/24,10.66.66.0/24
